### ISSUE TITLE
可否增设统计时间60分钟、12~48小时吗？

### ISSUE THREAD

**Issue by openwrtdiy** [muink/luci-app-netdata#1]
如果用户使用X86X64软路由时，内存和硬盘的可用空间都很大！应该能够存储一两天的统计数据。
当前netdata默认统计时长20分钟

**Comment by muink** [comment]
这些功能是在netdata.conf中配置的吗

**Comment by openwrtdiy** [comment]
> 这些功能是在netdata.conf中配置的吗

应该是
OpenWrt官方默认参数 https://github.com/openwrt/packages/blob/master/admin/netdata/files/netdata.conf

OpenWrt第三方参数 https://github.com/dlitz/openwrt-packages/blob/master/admin/netdata/files/netdata.conf

https://github.com/netdata/netdata/issues/3795

https://github.com/netdata/netdata/issues/5454

**Comment by muink** [comment]
最新版本[20221121](https://github.com/muink/luci-app-netdata/tree/v20221121)已经添加了`netdata.conf`编辑功能
