### ISSUE TITLE
Possibility to add uHTTP - HTTPS support?

### ISSUE THREAD

**Issue by LokeYourC3PH** [muink/luci-app-netdata#3]
When trying to load the Dashboard from within the Router while having HTTPS turned on with a self-signed certificate, it cannot load the page. The page has to be manually opened with the IP:Port. Would it be possible to support HTTPS loading within the Router's Administration page?

**Comment by LokeYourC3PH** [comment]
Trying to install the latest version after upgrading OpenWRT, also results in this:
![image](https://github.com/muink/luci-app-netdata/assets/5807595/646b4ccb-d6a7-436c-8ab5-e23f5266b2ce)

`netdata-ssl` is not a package I can find for download anywhere.

**Comment by muink** [comment]
The Netdata package from the official feeds of OpenWrt has removed SSL support, so it cannot support https without using nginx.
`netdata-ssl` is my rebuilt version of reverting this change and it can be found [here](https://fantastic-packages.github.io/packages/releases/)
You can install it by **manually uploading** or **adding custom feeds**

**Comment by LokeYourC3PH** [comment]
> The Netdata package from the official feeds of OpenWrt has removed SSL support, so it cannot support https without using nginx. `netdata-ssl` is my rebuilt version of reverting this change and it can be found [here](https://fantastic-packages.github.io/packages/releases/) You can install it by **manually uploading** or **adding custom feeds**

Thank you, I will install that one then~

Oh also, the latest version of luci-app-netdata cannot be installed on my Router (check image above). Could you update it for the latest snapshot (mipsel_24kc) :)?

**Comment by muink** [comment]
`luci-app-netdata` is universal architecture. After `netdata-ssl` is installed, `luci-app-netdata` should be installed normally.

**Comment by LokeYourC3PH** [comment]
> `luci-app-netdata` is universal architecture. After `netdata-ssl` is installed, `luci-app-netdata` should be installed normally.

The problem is that the dependency "libopenssl1.1" cannot be installed on my Router. Even though mipsel_24kc shows up under "[Architectures](https://openwrt.org/packages/pkgdata/libopenssl1.1)", it can't be found in the repository. And looking at https://downloads.openwrt.org/releases/22.03.2/packages/mipsel_24kc/packages/ , there is no libopenssl1.1 package there either.

I have libopenssl3 though.

**Comment by muink** [comment]
Because OpenWrt version >= 23.05 is upgraded `libopenssl1.1` to `libopenssl3`
And OpenWrt's Netdata currently does not support libopenssl3

Based on the above points, currently `netdata-ssl` also only supports OpenWrt version <= 22.03.
Unless OpenWrt official upgrades Netdata to 1.42.2 or newer version

https://downloads.openwrt.org/releases/22.03.2/packages/mipsel_24kc/base/libopenssl1.1_1.1.1w-1_mipsel_24kc.ipk
I'm not sure if installing this will work, might break software that relies on libopenssl3

**Comment by LokeYourC3PH** [comment]
> Because OpenWrt version >= 23.05 is upgraded `libopenssl1.1` to `libopenssl3` And OpenWrt's Netdata currently does not support libopenssl3
> 
> Based on the above points, currently `netdata-ssl` also only supports OpenWrt version <= 22.03. Unless OpenWrt official upgrades Netdata to 1.42.2 or newer version
> 
> https://downloads.openwrt.org/releases/22.03.2/packages/mipsel_24kc/base/libopenssl1.1_1.1.1w-1_mipsel_24kc.ipk I'm not sure if installing this will work, might break software that relies on libopenssl3

Thank you, then I'd rather wait for OpenWRT to update Netdata officially and add support for the library, rather than me possibly breaking stuff unintentionally. Netdata is running fine on the Router at the moment, but the LuCI app and the netdata-ssl packages cannot be installed for the moment, which is ok.
