### ISSUE TITLE
build architecture problem

### ISSUE THREAD

**Issue by attarchi** [muink/luci-app-netdata#6]
First of all, thank you very much for this nice package.

I tried installing it on an x86 device and got this error: "has no valid architecture, ignoring."

- Openwrt Version: 23.05.2
- CPU Architecture: i386_pentium4
- Package: luci-app-netdata	20230507
- Package source: https://fantastic-packages.github.io/packages/releases/23.05/packages/x86_64/luci/luci-app-netdata_20230507_all.ipk

**Comment by muink** [comment]
luci-app-netdata depends on [netdata-ssl](https://github.com/muink/openwrt-netdata-ssl/commit/a09fe222ff07fe4d286b550c2fa0597ddd19413c), incompatible with official version of openwrt.
And [Arch List](https://github.com/fantastic-packages/packages/blob/master/.github/workflows/AutoBuild.yml#L61) of [AutoBuild](https://github.com/fantastic-packages/packages/actions/workflows/AutoBuild.yml) action does not include `i386_pentium4`. You can fork fantastic-packages repo and modify the matrix to add `i386_pentium4`.

**Comment by muink** [comment]
I noticed that your fork build failed, this may be because the repo variables is not set.
I have recently added a [fork guide](https://github.com/fantastic-packages/packages/blob/master/ForkTheProject.md), if you need it you can try it again.
